Update README
PyBites-Open-Source/pybites-carbon pull request #22
Opened 2024-11-15 07:12 UTC by cmsato09

- Added additional installation instructions with uv and uv tool
- Include playwright install step
- Removed mentions of Selenium

2024-11-15 11:01 UTC, bbelderbos requested changes
Thanks for this, I have a few comments / preferences, what do you think?

2024-11-15 11:01 UTC, bbelderbos commented on README.md
> +### Install as a uv tool
I would say "as a standalone tool"

I think this is the more common scenario, so could you put this first?

2024-11-15 17:21 UTC, cmsato09 commented on README.md
>  pip install pybites-carbon
Reorder makes sense.
I think I've forgotten how to make a venv the official way because of `uv venv`

2024-11-15 17:24 UTC, cmsato09 commented on README.md
> +1. Create virtual environment
Yes it's redundant, but I think better mentioned than not. Just in case.

2024-11-15 17:26 UTC, cmsato09 commented on README.md
> +# or add as a dev dependency
I kind of threw it in there as a just-in-case thing, but I see your point.

2024-11-15 21:39 UTC, cmsato09 commented
@bbelderbos 
Made some revisions and also removed the YouTube link from the pyproject.toml file.

2024-11-18 15:51 UTC, bbelderbos approved these changes
Thanks.

2024-11-18 15:51 UTC, merged